apiVersion: v1
kind: Namespace
metadata:
  name: apisrv
  labels:
    name: apisrv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nanoapi-deployment
  namespace: apisrv
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apisrv
  template:
    metadata:
      labels:
        app: apisrv
    spec:
      containers:
      - name:  nanoapi
        image:  wave.md/repo/nanoapi2:230722-8234e29
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nanoapi-deployment
  namespace: apisrv
spec:
  selector:
    app: apisrv
  ports:
  - port: 30800
    targetPort: 8080
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nanoapi-ingress
  namespace: apisrv
spec:
  ingressClassName: ingress
  rules:
  - host: java.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nanoapi-deployment
            port:
              number: 65535